project:
  type: website
  output-dir: latest

format:
  html: 
    css: styles.css

website:
  repo-url: https://github.com/transparencia-mg/viz-metadados-frictionless
  repo-actions: [edit, issue]
  navbar:
    left:
    - href: index.md
      text: Home
    right:
      - href: apresentacoes.md
      - href: testes-usabilidade.md
      - href: legislacao.md
      - href: glossario.md
      - icon: github
        href: https://github.com/transparencia-mg/viz-metadados-frictionless
  sidebar:
    style: floating
    search: true
    contents:
      - section: Visão Geral
        contents: 
          - index.md
          - motivacao-contexto.md
      - section: Produção
        contents:
          - necessidades/web-app-criacao.md
          - necessidades/web-app-atualizacao.md
          - necessidades/web-app-validacao.md
          - necessidades/web-app-catalogacao.md
      - section: Publicação
        contents:
          - necessidades/importacao.md
          - necessidades/atualizacao.md
      - section: Distribuição
        contents: 
          - necessidades/identidade-visual.md
          - necessidades/validacao.md
          - necessidades/web-analytics.md
          - necessidades/dataset-namespace.md
          - necessidades/dataset-archive.md
      - section: Acesso
        contents:
          - necessidades/exportacao.md
          - necessidades/leitura.md
      - section: Uso
        contents:
          - necessidades/dicionario-dados.md
          - necessidades/diagramas.md
          - necessidades/metadados.md
          - necessidades/estatisticas-descritivas.md
          

comments:
  hypothesis: true