project:
  type: website
  output-dir: latest

website:
  repo-url: https://github.com/transparencia-mg/viz-metadados-frictionless
  repo-actions: [edit, issue]
  navbar:
    left:
    - href: index.md
      text: Home
    right:
      - href: testes-usabilidade.md
      - href: legislacao.md
      - href: glossario.md
      - icon: github
        href: https://github.com/transparencia-mg/viz-metadados-frictionless
  sidebar:
    style: floating
    search: true
    contents:
      - section: Visão Geral
        contents: 
          - index.md
          - motivacao-contexto.md
      - section: Produção
        contents:
          - necessidades/criacao.md
          - necessidades/validacao.md
      - section: Publicação
        contents:
          - necessidades/catalogacao.md
          - text: Importação de metadados
            href: necessidades/importacao-metadados.md
          - text: Importação de dados
            href: necessidades/importacao-dados.md
      - section: Distribuição
        contents: 
          - necessidades/identidade-visual.md
          - necessidades/metadados-validacao.md
      - section: Acesso
        contents:
          - necessidades/exportacao.md
          - necessidades/leitura.md
      - section: Uso
        contents:
          - necessidades/metadados-tableschema.md
          - necessidades/diagramas.md
          - necessidades/metadados-recurso.md
          - necessidades/metadados-stats.md
          

comments:
  hypothesis: true