project:
  type: website
  output-dir: latest

format:
  html: 
    css: styles.css

website:
  repo-url: https://github.com/transparencia-mg/viz-metadados-frictionless
  repo-actions: [edit, issue]
  navbar:
    left:
    - href: index.md
      text: Home
    right:
      - href: apresentacoes.md
      - href: testes-usabilidade.md
      - href: legislacao.md
      - href: glossario.md
      - icon: github
        href: https://github.com/transparencia-mg/viz-metadados-frictionless
  sidebar:
    style: floating
    search: true
    contents:
      - section: Visão Geral
        contents: 
          - index.md
      - section: Épicos
        contents:
          - necessidades/producao.md
          - necessidades/publicacao.md
          - necessidades/distribuicao.md
          - necessidades/acesso.md
          - necessidades/uso.md         

comments:
  hypothesis: true