project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/transparencia-mg/viz-metadados-frictionless
  repo-actions: [edit, issue]
  navbar:
    left:
    - href: index.md
      text: Home
    right:
      - href: glossario.md
      - icon: github
        href: https://github.com/transparencia-mg/viz-metadados-frictionless
  sidebar:
    style: floating
    search: true
    contents:
      - section: Visão Geral
        contents: 
          - index.md
          - motivacao-contexto.md
      - section: Produção
        contents:
          - criacao.md
      - section: Publicação
        contents:
          - catalogacao.md
          - text: Importação de metadados
            href: importacao-metadados.md
          - text: Importação de dados
            href: importacao-dados.md
      - section: Visualização
        contents:
          - metadados-tableschema.md
          - diagramas.md
          - metadados-recurso.md
          - metadados-validacao.md
          - metadados-stats.md
          - identidade-visual.md
      - section: Acesso
        contents:
          - exportacao.md
          - leitura.md
          

comments:
  hypothesis: true