---
title: Legislação
---

### [Decreto 45969, de 24/05/2012](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=DEC&num=45969&comp=&ano=2012&aba=js_textoAtualizado)

> Regulamenta o Acesso à Informação no âmbito do Poder Executivo.

### [Decreto 48383, de 18/03/2022](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=DEC&num=48383&comp=&ano=2022)

> Regulamenta o Governo Digital Estadual, no âmbito da Administração Pública direta, autárquica e fundacional do Poder Executivo.


Art. 25 – O compartilhamento de dados entre os órgãos e as entidades, resultado dos mecanismos de interoperabilidade, é categorizado em três níveis, de acordo com sua confidencialidade:

I – compartilhamento amplo, quando se tratar de dados públicos que não estão sujeitos a nenhuma restrição de acesso, cuja divulgação deve ser pública e garantida a qualquer interessado, na forma da legislação;

[...]

Art. 27 – O compartilhamento amplo de dados dispensa autorização prévia pelo gestor de dados e será realizado pelos canais existentes para dados abertos e para transparência ativa, na forma da legislação.

[...]

§ 3º – Os dados de compartilhamento amplo serão catalogados no Portal de Dados Abertos do Estado de Minas Gerais, https://www.dados.mg.gov.br, em formato aberto.